title: Samridha Murali
description: Software Engineer @ Apple
theme: jekyll-theme-slate
url: "https://msam13.github.io/"
baseurl: "/"
author:
  name: Samridha Murali
  email: msamridha16@gmail.com
  linkedin: "https://www.linkedin.com/in/m-samridha/"
  twitter: "https://x.com/murali_samridha"

# Custom CSS
sass:
  style: compressed

include:
  - assets/css/custom.css

# Custom CSS file
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      css: /assets/css/custom.css
